name: PHP Syntax Check
on:
  push:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '5.6.40'

    - name: Install PHP Coding Standards Fixer
      run: composer global require friendsofphp/php-cs-fixer

    - name: Check PHP syntax
      run: |
        composer global remove friendsofphp/php-cs-fixer
        composer global require friendsofphp/php-cs-fixer
        ~/.composer/vendor/bin/php-cs-fixer --version
        ~/.composer/vendor/bin/php-cs-fixer --diff --dry-run -v fix

        