name: PHP Syntax Check

on:
  push:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 5.6.40

    - name: Run PHP syntax check
      run: php -l C:\xampp\htdocs\bas
        