name: PHP Syntax Check

on:
  push:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 5.6.40

    - name: Check PHP syntax
      run: |
        cd C:\xampp\htdocs\bas
        composer req --dev phpstan/phpstan phpstan/phpstan-doctrine phpstan/phpstan-phpunit phpstan/phpstan-symfony
        